# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard's Log
brief-intro: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://precompiler.github.io"

permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username:
github_username: precompiler
email: lishengyin.msn@hotmail.com
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
duoshuo_shortname: 
disqus_shortname: 

# statistic analysis
baidu_tongji_id: 
google_analytics_id: UA-123734950-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001